#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u32)]
pub enum VirtualKey {
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    Space,
    Enter,
    Tab,
    Backspace,
    Esc,
    CapsLock,
    Shift,
    Control,
    Alt,
    Left,
    Right,
    Up,
    Down,
    PageUp,
    PageDown,
    Home,
    End,
    Delete,
    Grave,
    Minus,
    Equal,
    LeftBrace,
    RightBrace,
    Backslash,
    Semicolon,
    Apostrophe,
    Comma,
    Dot,
    Slash,
}

impl std::fmt::Display for VirtualKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl std::str::FromStr for VirtualKey {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "a" => Ok(Self::A),
            "b" => Ok(Self::B),
            "c" => Ok(Self::C),
            "d" => Ok(Self::D),
            "e" => Ok(Self::E),
            "f" => Ok(Self::F),
            "g" => Ok(Self::G),
            "h" => Ok(Self::H),
            "i" => Ok(Self::I),
            "j" => Ok(Self::J),
            "k" => Ok(Self::K),
            "l" => Ok(Self::L),
            "m" => Ok(Self::M),
            "n" => Ok(Self::N),
            "o" => Ok(Self::O),
            "p" => Ok(Self::P),
            "q" => Ok(Self::Q),
            "r" => Ok(Self::R),
            "s" => Ok(Self::S),
            "t" => Ok(Self::T),
            "u" => Ok(Self::U),
            "v" => Ok(Self::V),
            "w" => Ok(Self::W),
            "x" => Ok(Self::X),
            "y" => Ok(Self::Y),
            "z" => Ok(Self::Z),
            "0" | "digit0" => Ok(Self::Digit0),
            "1" | "digit1" => Ok(Self::Digit1),
            "2" | "digit2" => Ok(Self::Digit2),
            "3" | "digit3" => Ok(Self::Digit3),
            "4" | "digit4" => Ok(Self::Digit4),
            "5" | "digit5" => Ok(Self::Digit5),
            "6" | "digit6" => Ok(Self::Digit6),
            "7" | "digit7" => Ok(Self::Digit7),
            "8" | "digit8" => Ok(Self::Digit8),
            "9" | "digit9" => Ok(Self::Digit9),
            "space" => Ok(Self::Space),
            "enter" => Ok(Self::Enter),
            "tab" => Ok(Self::Tab),
            "backspace" => Ok(Self::Backspace),
            "esc" => Ok(Self::Esc),
            "capslock" => Ok(Self::CapsLock),
            "shift" => Ok(Self::Shift),
            "control" | "ctrl" => Ok(Self::Control),
            "alt" => Ok(Self::Alt),
            "left" => Ok(Self::Left),
            "right" => Ok(Self::Right),
            "up" => Ok(Self::Up),
            "down" => Ok(Self::Down),
            "pageup" => Ok(Self::PageUp),
            "pagedown" => Ok(Self::PageDown),
            "home" => Ok(Self::Home),
            "end" => Ok(Self::End),
            "delete" => Ok(Self::Delete),
            "grave" | "`" => Ok(Self::Grave),
            "minus" | "-" => Ok(Self::Minus),
            "equal" | "=" => Ok(Self::Equal),
            "leftbrace" | "[" => Ok(Self::LeftBrace),
            "rightbrace" | "]" => Ok(Self::RightBrace),
            "backslash" | "\\" => Ok(Self::Backslash),
            "semicolon" | ";" => Ok(Self::Semicolon),
            "apostrophe" | "'" => Ok(Self::Apostrophe),
            "comma" | "," => Ok(Self::Comma),
            "dot" | "." => Ok(Self::Dot),
            "slash" | "/" => Ok(Self::Slash),
            _ => Err(()),
        }
    }
}

impl VirtualKey {
    pub fn to_u32(self) -> u32 {
        self as u32
    }
}
